logging:
  level:
    #    io:
    #      netty: debug
    reactor: warn

spring:

  data:
    mongodb:
      host: mongo_user
      port: 27017
      database: webflux_mongo_demo
#      uri: mongodb://mongo_user:27017/webflux_mongo_demo